spring:
  application:
    name: tlias-web-management
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD:1234}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.chy.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

jwt:
  secret: ${JWT_SECRET:aXRoZWltYQ==}
  expiration: 900000

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai3041226865
    region: cn-beijing